### ISSUE TITLE
stored procedures

### ISSUE THREAD

**Issue by ghost** [TheBosZ/dabl-dart#1]
allow to use stored procedures would be useful.

**Comment by TheBosZ** [comment]
I'm trying to think of a way that an ORM can provide easy access to a stored procedure. How would you see this working?

**Comment by ghost** [comment]
is it a ORM, Or a code generator that gens the Data Access Layer ?

If its a code generator then its easy to reflect off the DB. I did one for Oracle about 8 years ago for a large team, so that th DAL layer was fully generated.

let me know, as i am curious

**Comment by TheBosZ** [comment]
It's mostly a code generator. You can see the result of running the generator here: https://github.com/TheBosZ/rollcall/blob/master/lib/models/base/base_attendance.dart

**Comment by ghost** [comment]
ah thats lucky.  So its not a true ORM. No reflection.

the reason i brought this up is ONLY because the select query language you have is so limited.
So if the select language is limited, its possible to just put the logic at the DB level as stored Procs, and then just call it from the Dart DAL.

At the dart layer, all you need to worry about is the input variables, and not have to worry then about the SQL dialect so much.

is a quick way to make this very powerful perhaps ???

**Comment by TheBosZ** [comment]
I'm not sure I understand.

DABL allows you to only worry about the input variables and not worry about the SQL dialect. It uses the [DDO library](https://github.com/TheBosZ/pdo-dart) which is an abstraction layer.

Underneath the covers, it uses an object-oriented query builder named [DABL Query](https://github.com/TheBosZ/dabl-query).

If you absolutely wanted to call stored procedures, you can override the save() method in the models to call the stored procedure instead of the default method.

Does that help?

**Comment by ghost** [comment]
I think I am wrong or we don't understand each other.

I can't try it right now, but will give the examples a try.

Have you got any benchmarks ?
How is the speed under dart I wonder ?

**Comment by TheBosZ** [comment]
Closing as the user has been deleted and no further information was provided.
